# Generated by Django 5.1.7 on 2025-03-08 11:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0002_remove_stadiumbooking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stadiumbooking',
            name='unique_booking',
        ),
        migrations.RemoveField(
            model_name='stadiumbooking',
            name='end_time',
        ),
        migrations.AddField(
            model_name='stadiumbooking',
            name='hours',
            field=models.IntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='stadiumbooking',
            constraint=models.UniqueConstraint(fields=('stadium', 'start_time'), name='unique_booking'),
        ),
    ]
