# Generated by Django 5.1.7 on 2025-03-08 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0003_remove_stadiumbooking_unique_booking_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StadiumBooking',
        ),
    ]
